# This is a basic workflow to help you get started with Actions

name: test_and_coverage

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other packages
        run: pip install -U tox-travis coveralls
      - name: Run Tox
        # Run tox using the version of Python in `PATH`
        run: tox -e py
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Coverage
        run: |
          coverage run --source=creopyson setup.py test
          coveralls
