# This is a basic workflow to help you get started with Actions

name: test_and_coverage

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
      - name: Run Tox
        # Run tox using the version of Python in `PATH`
        run: tox -e py
          echo Add other actions to build,
          echo test, and deploy your project.
      # - name: Coverage
      #   run: |
      #     pip install -U pytest pytest-cov
      #     python -m pytest --cov-report xml
      # - name: Coveralls
      #   uses: coverallsapp/github-action@master
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     path-to-lcov: coverage.xml
      - name: install coverages stuffs
        run: |
          pip install -U coveralls coverage pytest pytest-cov
          coverage run --source=creopyson setup.py test
          coveralls
        with:
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
      # - name: Coveralls
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     coveralls
      # - name: Test with pytest
      #   run: |
      #     pytest
      # - name: Coveralls
      #   uses: coverallsapp/github-action@master
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      # - name: Test with pytest
      #   run: |
      #     pip install pytest pytest-cov
      #     python -m pytest --cov-report xml
      #     coveralls --output=coverage.xml
      #     coveralls-lcov -v -n coverage.info > coverage.xml
      # - name: Coveralls
      #   uses: coverallsapp/github-action@master
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     path-to-lcov: coverage.xml
